#!/bin/sh
# Searches the current Nix store for the current activated version of a given package.
# Note to run this script, you must add '.' in front of it to run it in the current subsell. You can alias the command to do this automatically.

if [ -n "$1" ]; then
  npath=$(nix path-info $(which $1))
  echo $npath

  cd $npath
else
  echo "No valid package. exiting."
  exit 1
fi
