#!/usr/bin/env bash
# Combines rebuilding, garbage collection and optimizing the system

if [[ $(whoami) == "root" ]]; then
  nixos-rebuild switch --upgrade && \
  nix-collect-garbage --delete-older-than 7d && \
  nix optimise-store
else
  echo "These commands must be run as root."
  exit 1
fi
