#!/usr/bin/env bash
# Updates the shortcuts file.
# Christopher Birkbeck 2018

# Traverse the entire Scripts directory to find any new files.
function add_new {
  cd "$1" || { echo "Error. Cannot find or make $1 Exiting." >2; Exit 1; }

  for file in *; do
    if [[ -d $file ]] && [[ $file != ".git" ]]; then
      add_new "$file"
    elif [[ "$file" == "README.md" ]]; then
      continue
    else
      if [[ $file =~ (.*).sh ]]; then
        name=${file:0:-3}
      else
        name=$file
      fi

      orginal=$(readlink -f "$file")

      echo -e "alias $name=\"$orginal\"" >> "$HOME/Scripts/shortcuts"
    fi
  done

  cd ..
}

# Removes any duplicated lines.
function remove_duplicates {
  awk '!seen[$0]++' "$HOME/Scripts/shortcuts" > "$HOME/Scripts/shortcuts-tmp"
  rm "$HOME/Scripts/shortcuts"
  mv "$HOME/Scripts/shortcuts-tmp" "$HOME/Scripts/shortcuts"
}

# Verifies any existing entries still exist.
function verify {
  while IFS= read -r line; do
    current=$(sed -E -e 's,alias (.*)=\"(.*)\",\2,g' <<< "$line")

    if [[ -f "$current" ]]; then
      echo "Found $current"
      continue
    else
      sed -i -E -e "s,alias (.*)=\"$current\",,g" "$HOME/Scripts/shortcuts"
    fi
  done <"$HOME/Scripts/shortcuts"
}

cd "$HOME/Scripts" || mkdir "$HOME/Scripts" || { echo "Error. Cannot find or make $HOME/Scripts. Exiting." >2; Exit 1; }

add_new "$HOME/Scripts"
remove_duplicates
verify
