#!/usr/bin/env bash
# Describe script here.
# Created on Monday December 24, 2018.
# Created by Christopher Birkbeck

if [ "$( tput colors )" -ge 256 ]; then
    colours="xterm256"
else
    colours="ansi"
fi

for file in "$@"; do
    highlight --replace-tabs=8 --out-format="${colours}" --style=pablo --force -- "$file" | cat
done
