#!/usr/bin/env bash
# Combines rebuilding, garbage collection and optimizing the system

nixos-rebuild switch --upgrade | tee /tmp/lastupdate.log && \
nix-collect-garbage --delete-older-than 14d | tee -a /tmp/lastupdate.log && \
nix-store --optimise | tee -a /tmp/lastupdate.log
